spring:
  datasource:
    url: jdbc:mysql://localhost:3306/COVID?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop  #update
    show-sql: true 
